import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import Navbar from "./Components/Nav";
import AOSProvider from "./Components/AosProvider";
import Footer from "./Components/Footer";

const playfairDisplay = Playfair_Display({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

const manrope = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${playfairDisplay.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AOSProvider />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
